// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/jonatan5524/side-projects-manager/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// ParentDirectoryUsecase is an autogenerated mock type for the ParentDirectoryUsecase type
type ParentDirectoryUsecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *ParentDirectoryUsecase) GetAll() ([]*model.ParentDirectory, error) {
	ret := _m.Called()

	var r0 []*model.ParentDirectory
	if rf, ok := ret.Get(0).(func() []*model.ParentDirectory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ParentDirectory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: _a0
func (_m *ParentDirectoryUsecase) Put(_a0 model.ParentDirectory) (model.ParentDirectory, error) {
	ret := _m.Called(_a0)

	var r0 model.ParentDirectory
	if rf, ok := ret.Get(0).(func(model.ParentDirectory) model.ParentDirectory); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.ParentDirectory)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.ParentDirectory) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
