// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/jonatan5524/side-projects-manager/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// ProjectUsecase is an autogenerated mock type for the ProjectUsecase type
type ProjectUsecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *ProjectUsecase) Delete(_a0 model.Project) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Project) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByPath provides a mock function with given fields: _a0
func (_m *ProjectUsecase) DeleteByPath(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ProjectUsecase) GetAll() ([]*model.Project, error) {
	ret := _m.Called()

	var r0 []*model.Project
	if rf, ok := ret.Get(0).(func() []*model.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
